version: 0.2

env:
  variables: S3_BUCKET=ottwatch-webapp
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 cp --recursive --acl public-read ./build/ s3://${S3_BUCKET}/
      # - aws s3 sync build/ s3://${DeployBucket}/ --exclude .DS_Store
      # set the cache-control headers for service-worker.js to prevent
      # browser caching
      - >
        aws s3 cp --acl public-read
        --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        ./build/service-worker.js s3://${S3_BUCKET}/
      # set the cache-control headers for index.html to prevent
      # browser caching
      - >
        aws s3 cp --acl public-read 
        --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        ./build/index.html s3://${S3_BUCKET}/
      # invalidate the CloudFront cache for index.html and service-worker.js
      # to force CloudFront to update its edge locations with the new versions
      # - >
      #   aws cloudfront create-invalidation --distribution-id ${Distribution}
      #   --paths /index.html /service-worker.js
artifacts:
  base-directory: build
  files:
    - "**/*"
