
export const genres = {
  action: "./action.svg",
  adventure: "./adventure.svg",
  animation: "./animation.svg",
  comedy: "./comedy.svg",
  crime: "./crime.svg",
  documentary: "./documentary.svg",
  drama: "./drama.svg",
  family: "./family.svg",
  fantasy: "./fantasy.svg",
  history: "./history.svg",
  horror: "./horror.svg",
  inside_bg_top: "./inside_bg_top.svg",
  music: "./music.svg",
  mystery: "./mystery.svg",
  normal_botton_shadow: "./normal.svg",
  romance: "./romance.svg",
  science_fiction: "./science_fiction.svg",
  thriller: "./thriller.svg",
  tv_movies: "./tv_movies.svg",
  war: "./war.svg",
  western: "./western.svg",
};
