/* eslint-disable global-require */
const Images = {
  popcornImage: require('https://images.ottplay.com/static/popcorn_image.png'),
  intersectionImage: require('https://images.ottplay.com/static/Intersection_138.png'),
  forwordArrowIcon: require('https://images.ottplay.com/static/forwoed_arrow_icon.png'),
  closeIcon: require('https://images.ottplay.com/static/close.png'),
  PrimeVideo: require('https://images.ottplay.com/static/PrimeVideo.png'),
  Discovery: require('https://images.ottplay.com/static/Discovery.png'),
  Disney_Hotstar: require('https://images.ottplay.com/static/Disney_Hotstar.png'),
  Eros_Now: require('https://images.ottplay.com/static/Eros_Now.png'),
  HBO: require('https://images.ottplay.com/static/HBO.png'),
  Sony: require('https://images.ottplay.com/static/Sony.png'),
  Voot: require('https://images.ottplay.com/static/Voot.png'),
  Zees: require('https://images.ottplay.com/static/Zees.png'),
  ALT: require('https://images.ottplay.com/static/ALT.png'),
  recommendationLoader: require('https://images.ottplay.com/static/recommendationLoader.png'),
  inside_bg_top: require('https://images.ottplay.com/static/inside_bg_top.png'),
  home_bg: require('https://images.ottplay.com/static/home_bg.png'),
  backgroundImage: require('https://images.ottplay.com/static/home_bg.png'),
  // home
  charming_douche: require('https://images.ottplay.com/static/charming_douche.png'),
  imdb: require('https://images.ottplay.com/static/reel_logo.png'),
  section_img: require('https://images.ottplay.com/static/section_img.png'),
  circle_plus: require('https://images.ottplay.com/static/circle_plus.png'),
  circle_with_dots: require('https://images.ottplay.com/static/circle_with_dots.png'),
  Intersection86: require('https://images.ottplay.com/static/Intersection86.png'),
  Image4: require('https://images.ottplay.com/static/Image4.png'),
  Image51: require('https://images.ottplay.com/static/Image51.png'),
  onboardTopBackgroundImage: require('https://images.ottplay.com/static/onboard_bg_top.png'),
  logo: require('https://images.ottplay.com/static/logo.png'),
  settingsIcon: require('https://images.ottplay.com/static/settings.png'),
  notificationIcon: require('https://images.ottplay.com/static/notification.png'),
  arrowIcon: require('https://images.ottplay.com/static/arrow-icon.png'),
  clearIcon: require('https://images.ottplay.com/static/clear-icon.png'),
  cancelIconBanner: require('https://images.ottplay.com/static/Group8344.png'),

  // Tab icons
  homeIcon: require('https://images.ottplay.com/static/tab-icons/homeIcon.png'),
  searchIcon: require('https://images.ottplay.com/static/tab-icons/search.png'),
  watchlistIcon: require('https://images.ottplay.com/static/tab-icons/watchlist.png'),
  forYouIcon: require('https://images.ottplay.com/static/tab-icons/for-you.png'),
  meIcon: require('https://images.ottplay.com/static/tab-icons/me.png'),
  homeIconSelected: require('https://images.ottplay.com/static/tab-icons/home-selected.png'),
  searchIconSelected: require('https://images.ottplay.com/static/tab-icons/search-selected.png'),
  forYouIconSelected: require('https://images.ottplay.com/static/tab-icons/for-you-selected.png'),
  WatchlistIconSelected: require('https://images.ottplay.com/static/tab-icons/watchlist-selected.png'),
  meIconSelected: require('https://images.ottplay.com/static/tab-icons/me-selected.png'),
  tabItemHighlight: require('https://images.ottplay.com/static/tab-icons/tab-item-highlight.png'),
  skip: require('https://images.ottplay.com/static/Skip.png'),
  dislike: require('https://images.ottplay.com/static/Dislike.png'),
  heart: require('https://images.ottplay.com/static/Heart.png'),
  swipeRight: require('https://images.ottplay.com/static/Swiperight.png'),
  swipeLeft: require('https://images.ottplay.com/static/Swipeleft.png'),
  swipeUp: require('https://images.ottplay.com/static/Swipeup.png'),
  rectangleSplitter: require('https://images.ottplay.com/static/Rectangle2962.png'),
  cardBackgroundImage: require('https://images.ottplay.com/static/Image30.png'),
  moreCardImage: require('https://images.ottplay.com/static/moreCards.png'),
  //
  play: require('https://images.ottplay.com/static/play.png'),
  circle_close: require('https://images.ottplay.com/static/circle_close.png'),
  circle_dislike_active: require('https://images.ottplay.com/static/dislike_active_30.png'),
  circle_heart: require('https://images.ottplay.com/static/circle_heart.png'),
  circle_active_heart: require('https://images.ottplay.com/static/like_active_30.png'),
  circle_add_to_wl: require('https://images.ottplay.com/static/add_to_wl_30.png'),
  circle_add_toacitve_wl: require('https://images.ottplay.com/static/add_to_active_wl.png'),
  delete: require('https://images.ottplay.com/static/delete.png'),
  search: require('https://images.ottplay.com/static/search.png'),
  addReview: require('https://images.ottplay.com/static/addReview.png'),
  share: require('https://images.ottplay.com/static/Share.png'),
  selectMark: require('https://images.ottplay.com/static/add_to_wl_active.png'),
  circle_cancel: require('https://images.ottplay.com/static/circle_cancel.png'),
  circle_heart40: require('https://images.ottplay.com/static/circle_heart40.png'),
  circle_addWatch: require('https://images.ottplay.com/static/add_to_wl.png'),
  hide_wl: require('https://images.ottplay.com/static/hide_wl.png'),
  adImage: require('https://images.ottplay.com/static/adImage.png'),
  playIcon: require('https://images.ottplay.com/static/PlayIcon.png'),
  add_to_wl: require('https://images.ottplay.com/static/add_to_wl.png'),
  add_to_wl_active: require('https://images.ottplay.com/static/add_to_wl_active.png'),
  dislike_active: require('https://images.ottplay.com/static/dislike_active.png'),
  like_active: require('https://images.ottplay.com/static/like_active.png'),
  review_active: require('https://images.ottplay.com/static/review_active.png'),
  share_active: require('https://images.ottplay.com/static/share_active.png'),
  wl_icon: require('https://images.ottplay.com/static/wl_icon.png'),
  whiteCloseIcon: require('https://images.ottplay.com/static/whiteCloseIcon.png'),
  activeLike: require('https://images.ottplay.com/static/like_active.png'),
  activeDislike: require('https://images.ottplay.com/static/dislike_active.png'),
  activeReview: require('https://images.ottplay.com/static/review_active.png'),
  activeShare: require('https://images.ottplay.com/static/share_active.png'),
  clearIconPink: require('https://images.ottplay.com/static/ClearIcon.png'),
  video_thumbinal: require('https://images.ottplay.com/static/video_thumbinal.png'),
  JOKER_Trailer: require('https://images.ottplay.com/static/JOKER_Trailer.mp4'),
  share_icon: require('https://images.ottplay.com/static/share_icon.png'),
  trailer_play_icon: require('https://images.ottplay.com/static/trailer_play.png'),
  trailer_btn: require('https://images.ottplay.com/static/trailer.png'),
  trailer_image: require('https://images.ottplay.com/static/trailer_image.png'),
  watch: require('https://images.ottplay.com/static/watch.png'),
  downArrowMark: require('https://images.ottplay.com/static/downArrowMark.png'),
  callender: require('https://images.ottplay.com/static/callender.png'),
  dimond: require('https://images.ottplay.com/static/dimond.png'),
  radio: require('https://images.ottplay.com/static/radio.png'),
  defaultSwitch: require('https://images.ottplay.com/static/defaultSwitch.png'),
  activeSwitch: require('https://images.ottplay.com/static/activeSwitch.png'),

  // settings Screend default
  listVeiwBackground: require('https://images.ottplay.com/static/Group8346.png'),
  ic_cast_connected: require('https://images.ottplay.com/static/ic_cast_connected_24px.png'),
  shareFeedback: require('https://images.ottplay.com/static/emotion.png'),
  languagesSettings: require('https://images.ottplay.com/static/Group7727.png'),
  privacryPolicy: require('https://images.ottplay.com/static/lock-open.png'),
  signInIcon: require('https://images.ottplay.com/static/logout.png'),
  logoutIcon: require('https://images.ottplay.com/static/logoutL.png'),
  notification: require('https://images.ottplay.com/static/notificationSettings.png'),
  rateMore: require('https://images.ottplay.com/static/Path28306.png'),
  AboutUsIcon: require('https://images.ottplay.com/static/question.png'),
  faqIcon: require('https://images.ottplay.com/static/questionFAQ.png'),
  provider: require('https://images.ottplay.com/static/satellite-dish.png'),
  reportaProblem: require('https://images.ottplay.com/static/Group7729.png'),
  onboardTips: require('https://images.ottplay.com/static/Group7728.png'),

  // settings Screend active
  backward_arrow: require('https://images.ottplay.com/static/backward_arrow.png'),
  ic_cast_connected_active: require('https://images.ottplay.com/static/ic_cast_connected_24px_active.png'),
  shareFeedback_active: require('https://images.ottplay.com/static/emotion_active.png'),
  languagesSettings_active: require('https://images.ottplay.com/static/Group7727_active.png'),
  privacryPolicy_active: require('https://images.ottplay.com/static/lock-open_active.png'),
  signInIcon_active: require('https://images.ottplay.com/static/logout_active.png'),
  logoutIcon_active: require('https://images.ottplay.com/static/logoutL_active.png'),
  notification_active: require('https://images.ottplay.com/static/notification_active.png'),
  rateMore_active: require('https://images.ottplay.com/static/Path28306_active.png'),
  aboutUsIcon_active: require('https://images.ottplay.com/static/question_active.png'),
  faqIcon_active: require('https://images.ottplay.com/static/questionFAQ_active.png'),
  provider_active: require('https://images.ottplay.com/static/satellite-dish_active.png'),
  reportaProblem_active: require('https://images.ottplay.com/static/Group7729_active.png'),
  onboardTips_active: require('https://images.ottplay.com/static/Group7728_active.png'),

  // refine Screen default
  forwordArrowIconforSettings: require('https://images.ottplay.com/static/Group7563.png'),
  streamingSearvice: require('https://images.ottplay.com/static/Group7573.png'),
  contentType: require('https://images.ottplay.com/static/uqYdZ0.png'),
  price: require('https://images.ottplay.com/static/Group7593.png'),
  languages: require('https://images.ottplay.com/static/Group7981.png'),
  freepaid: require('https://images.ottplay.com/static/Group7984.png'),
  genres: require('https://images.ottplay.com/static/Group7588.png'),
  airdate: require('https://images.ottplay.com/static/Group7590.png'),
  contentrating: require('https://images.ottplay.com/static/Group7595.png'),
  ratings: require('https://images.ottplay.com/static/Group7597.png'),
  quality: require('https://images.ottplay.com/static/Group7591.png'),
  runtimeMinutes: require('https://images.ottplay.com/static/Group7594.png'),
  releaseYear: require('https://images.ottplay.com/static/Group7596.png'),

  // refine Screen active
  forwordArrowIconforSettings_active: require('https://images.ottplay.com/static/Group7563_active.png'),
  streamingSearvice_active: require('https://images.ottplay.com/static/Group8392_active.png'),
  contentType_active: require('https://images.ottplay.com/static/uqYdZ0_active.png'),
  price_active: require('https://images.ottplay.com/static/Group8399_active.png'),
  languages_active: require('https://images.ottplay.com/static/Group8393_active.png'),
  freepaid_active: require('https://images.ottplay.com/static/Group8396_active.png'),
  genres_active: require('https://images.ottplay.com/static/Group8394_active.png'),
  airdate_active: require('https://images.ottplay.com/static/Group8397_active.png'),
  contentrating_active: require('https://images.ottplay.com/static/Group8401_active.png'),
  ratings_active: require('https://images.ottplay.com/static/Group8395_active.png'),
  quality_active: require('https://images.ottplay.com/static/Group8397_active.png'),
  runtimeMinutes_active: require('https://images.ottplay.com/static/Group8400_active.png'),
  releaseYear_active: require('https://images.ottplay.com/static/Group8402_active.png'),
  actor_bg_img: require('https://images.ottplay.com/static/actor_bg_img.png'),
  award_bg_img: require('https://images.ottplay.com/static/award_bg_img.png'),
  activeItemBg_img: require('https://images.ottplay.com/static/Group8427.png'),
  //
  ihave_15min: require('https://images.ottplay.com/static/ihave_15min.png'),
  ihave_60min: require('https://images.ottplay.com/static/ihave_60min.png'),
  sort_icon: require('https://images.ottplay.com/static/sort_icon.png'),
  Zombies: require('https://images.ottplay.com/static/Zombies.png'),
  Space: require('https://images.ottplay.com/static/Space.png'),

  facebook: require('https://images.ottplay.com/static/facebook.png'),
  whatsapp: require('https://images.ottplay.com/static/whatsapp.png'),
  google: require('https://images.ottplay.com/static/google.png'),
  callbutton: require('https://images.ottplay.com/static/callbutton.png'),
};

export default Images;
